services:
  - type: web
    name: food-app
    env: python
    buildCommand: |
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    aptPackages:
      - tesseract-ocr